# Trusted repos for required apps
tap "barutsrb/tap", "https://github.com/BarutSRB/homebrew-tap", trusted: true
tap "nikitabobko/tap"

# CLI
brew "bat"
brew "btop"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "julia"
brew "make"
brew "neovim"
brew "python@3.14"
brew "ripgrep"
brew "rustup"
brew "starship"
brew "tmux"

#GUI
cask "anki"
cask "codex"
cask "font-caskaydia-cove-nerd-font"
cask "ghostty"
cask "helium-browser"
cask "librewolf"
cask "musicbrainz-picard"
cask "ollama-app"
cask "obsidian"
cask "barutsrb/tap/omniwm"
cask "qbittorrent"
cask "tailscale-app"
cask "tidal"
cask "vesktop"
cask "vlc"
cask "zed"
go "golang.org/x/tools/gopls"
go "gostow"
npm "corepack"
