[bar.default]
end = [ "notifications", "clipboard", "network", "bluetooth", "volume", "brightness", "battery" ]
margin_edge = 4
margin_ends = 4
position = "left"
radius = 4
start = [ "launcher", "workspaces" ]

[desktop_widgets]
enabled = false

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[shell]
font_family = "Noto Sans"

[theme]
builtin = "Rosé Pine"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-rainbow"

[wallpaper]
enabled = true

    [wallpaper.default]
    path = "/home/mlab/Pictures/Wallpapers/sekiro.jpg"

[weather]
unit = "imperial"

[widget.battery]
hide_when_plugged = true

[widget.control-center]
glyph = "niri"

[widget.network]
show_label = false

[widget.volume]
show_label = false

[widget.workspaces]
active_pill_size = 1.5
display = "none"
